name: Lock Threads

on:
  schedule:
    - cron: '0 1 2'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: ietf-tools/lock-threads@v3.1.1
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: 999999
          pr-inactive-days: 99999
          log-output: true
